In [14]:
import pandas as pd

In [15]:
data = {'FullName' :['Rucha N','Rohit K', 'Kedar P', 'Ankita G'],
       'Email' : ['Rucha07@gmail.com', 'Rohit.10@gmail.com', 'KedarTennis@gmail.com','Ankita21@gmail.com'],
        'Salary':[100000, 120000,90000,75000]
       }
df = pd.DataFrame(data)
df

   FullName                  Email  Salary
0   Rucha N      Rucha07@gmail.com  100000
1   Rohit K     Rohit.10@gmail.com  120000
2   Kedar P  KedarTennis@gmail.com   90000
3  Ankita G     Ankita21@gmail.com   75000

In [16]:
df['Bonus'] = df['Salary']*0.1
df

   FullName                  Email  Salary    Bonus
0   Rucha N      Rucha07@gmail.com  100000  10000.0
1   Rohit K     Rohit.10@gmail.com  120000  12000.0
2   Kedar P  KedarTennis@gmail.com   90000   9000.0
3  Ankita G     Ankita21@gmail.com   75000   7500.0

In [17]:
df[['FirstName', 'LastName']] = df['FullName'].str.split(' ', expand=True)
df

   FullName                  Email  Salary    Bonus FirstName LastName
0   Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha        N
1   Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit        K
2   Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar        P
3  Ankita G     Ankita21@gmail.com   75000   7500.0    Ankita        G

In [18]:
df['Age'] = [23,24,20,25]
df

   FullName                  Email  Salary    Bonus FirstName LastName  Age
0   Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha        N   23
1   Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit        K   24
2   Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar        P   20
3  Ankita G     Ankita21@gmail.com   75000   7500.0    Ankita        G   25

In [19]:
df.drop(columns=['LastName'],inplace=True)
df

   FullName                  Email  Salary    Bonus FirstName  Age
0   Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha   23
1   Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit   24
2   Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar   20
3  Ankita G     Ankita21@gmail.com   75000   7500.0    Ankita   25

In [20]:
row_data = {'FullName':'Parth P','Email': 'Parth11@gmail.com',
           'Salary':50000, 'Bonus': 5000.0, 
           'FirstName': 'Parth', 'Age':33}
df=pd.concat([df, pd.DataFrame([row_data])], ignore_index=True)
df

   FullName                  Email  Salary    Bonus FirstName  Age
0   Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha   23
1   Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit   24
2   Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar   20
3  Ankita G     Ankita21@gmail.com   75000   7500.0    Ankita   25
4   Parth P      Parth11@gmail.com   50000   5000.0     Parth   33

In [21]:
row_data = {'FullName':['Parth P', 'Priya M'],'Email': ['Parth11@gmail.com', 'Priya01@gmail.com'],
           'Salary':[50000, 60000], 'Bonus': [5000.0, 6000.0], 
           'FirstName': ['Parth', 'Priya'], 'Age':[33,30]}
df1 = pd.DataFrame(row_data)
df=pd.concat([df,df1], ignore_index=True)
df

   FullName                  Email  Salary    Bonus FirstName  Age
0   Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha   23
1   Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit   24
2   Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar   20
3  Ankita G     Ankita21@gmail.com   75000   7500.0    Ankita   25
4   Parth P      Parth11@gmail.com   50000   5000.0     Parth   33
5   Parth P      Parth11@gmail.com   50000   5000.0     Parth   33
6   Priya M      Priya01@gmail.com   60000   6000.0     Priya   30

In [22]:
df.drop(index=[3], inplace=True)
df

  FullName                  Email  Salary    Bonus FirstName  Age
0  Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha   23
1  Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit   24
2  Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar   20
4  Parth P      Parth11@gmail.com   50000   5000.0     Parth   33
5  Parth P      Parth11@gmail.com   50000   5000.0     Parth   33
6  Priya M      Priya01@gmail.com   60000   6000.0     Priya   30

In [23]:
df.drop_duplicates(inplace=True)
df

  FullName                  Email  Salary    Bonus FirstName  Age
0  Rucha N      Rucha07@gmail.com  100000  10000.0     Rucha   23
1  Rohit K     Rohit.10@gmail.com  120000  12000.0     Rohit   24
2  Kedar P  KedarTennis@gmail.com   90000   9000.0     Kedar   20
4  Parth P      Parth11@gmail.com   50000   5000.0     Parth   33
6  Priya M      Priya01@gmail.com   60000   6000.0     Priya   30