In [3]:
"""Name: Ashish Sameer Mulani
    PRN: 260240128007
    
    Name: Pranita Popat Lad
    PRN: 260240128028"""

'Name: Ashish Sameer Mulani\n    PRN: 260240128007\n\n    Name: Pranita Popat Lad\n    PRN: 260240128028'

In [4]:
                                                #Assignment 4

In [5]:
'''Pandas:
Q1. Create a DataFrame containing student information like Name, Age, Department, %Marks
a.	Display column names of the DF
b.	Show min/max and average marks
c.	Get unique values and student count for each Department'''

'Pandas:\nQ1. Create a DataFrame containing student information like Name, Age, Department, %Marks\na.\tDisplay column names of the DF\nb.\tShow min/max and average marks\nc.\tGet unique values and student count for each Department'

In [6]:
import pandas as pd

In [7]:
std_info = {'Name' : ['Aditya', 'Avani', 'Aditi', 'Ajay', 'Amol'],
       'Age' : [23, 25, 30, 28, 29],
       'Department': ['AI', 'DAC', 'BDA', 'AI', 'VLSI'],
       '%Marks' : [83, 85, 90, 88, 79]}
df = pd.DataFrame(std_info)
df

     Name  Age Department  %Marks
0  Aditya   23         AI      83
1   Avani   25        DAC      85
2   Aditi   30        BDA      90
3    Ajay   28         AI      88
4    Amol   29       VLSI      79

In [8]:
df.columns

Index(['Name', 'Age', 'Department', '%Marks'], dtype='str')

In [9]:
df['%Marks'].agg(['min', 'max', 'mean'])

min     79.0
max     90.0
mean    85.0
Name: %Marks, dtype: float64

In [10]:
df['Department'].value_counts()

Department
AI      2
DAC     1
BDA     1
VLSI    1
Name: count, dtype: int64

In [11]:
df['Department'].unique()

<StringArray>
['AI', 'DAC', 'BDA', 'VLSI']
Length: 4, dtype: str

In [12]:
'''Q2. Read csv file solar.csv
a.	Display all the plants with capacity > 500 MW'''

'Q2. Read csv file solar.csv\na.\tDisplay all the plants with capacity > 500 MW'

In [13]:
df=pd.read_csv('solar.csv')
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [14]:
filt=df['Installed Capacity (MW)']>500
df.loc[filt,['State']]

        State
0  California
1     Arizona
7     Florida

In [15]:
#b.	Display plant details for New York plant
df[df['State']=='New York']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

In [16]:
filt=df['State']=='New York'
df.loc[filt]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East

In [17]:
#c.	For all the plants display Average MW Per Plant and Generation (GWh)
df.filter(items=['Average MW Per Plant', 'Generation (GWh)'])

   Average MW Per Plant  Generation (GWh)
0                  15.3             10826
1                  22.5              2550
2                  21.6               557
3                   7.9               590
4                   5.9               235
5                  15.6               354
6                   4.1                84
7                  12.3               453

In [18]:
#d.	Sort the plants by Generation (GWh) (ascending) and Installed Capacity (MW)(descending)
df.sort_values(by=['Generation (GWh)', 'Installed Capacity (MW)'], ascending=[True, False])

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
7,Florida,15,535,12.3,453,South
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
1,Arizona,48,1078,22.5,2550,West
0,California,289,4395,15.3,10826,West

In [19]:
#e.	List top 5 plants for their Generation
df.head(5)

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East

In [20]:
top=df.sort_values(['Generation (GWh)'],ascending=[False]).head(5)
top

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
2,Nevada,11,238,21.6,557,West
7,Florida,15,535,12.3,453,South

In [21]:
#f.	Display all plant details for states – California, Nevada, Arizona and Texas
filt=df['State'].isin(['California','Nevada','Arizona','Texas'])
df.loc[filt]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
5,Texas,12,187,15.6,354,South

In [22]:
#g.	Group the plants by region, find – min/max capacity plant for each group
groups = df.groupby('Region')
min_plants = df.loc[groups['Installed Capacity (MW)'].idxmin()]
min_plants

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
6,New York,13,53,4.1,84,East
3,Chicago,33,261,7.9,590,North
5,Texas,12,187,15.6,354,South
2,Nevada,11,238,21.6,557,West

In [23]:
max_plants = df.loc[groups['Installed Capacity (MW)'].idxmax()]
max_plants

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
4,Connecticut,20,118,5.9,235,East
3,Chicago,33,261,7.9,590,North
7,Florida,15,535,12.3,453,South
0,California,289,4395,15.3,10826,West

In [24]:
#h.	Add following information to the existing details for the plants
	#North Carolina	148	669	4.5	1162	North
row_data = {'State':'North Carolina','Number of Solar Plants': 148,
           'Installed Capacity (MW)':669, 'Average MW Per Plant': 4.5, 
           'Generation (GWh)': 1162, 'Region':'North'}
new_df=pd.DataFrame([row_data])
df=pd.concat([df,new_df ], ignore_index=True)
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,North Carolina,148,669,4.5,1162,North

In [35]:
'''Q.3Read csv gapminder2007.csv
a.	Display data for all Asian countries'''

'Q.3Read csv gapminder2007.csv\na.\tDisplay data for all Asian countries'

In [25]:
df=pd.read_csv('gapminder2007.csv')
df

                country         pop continent  lifeExp     gdpPercap
0           Afghanistan  31889923.0      Asia   43.828    974.580338
1               Albania   3600523.0    Europe   76.423   5937.029526
2               Algeria  33333216.0    Africa   72.301   6223.367465
3                Angola  12420476.0    Africa   42.731   4797.231267
4             Argentina  40301927.0  Americas   75.320  12779.379640
..                  ...         ...       ...      ...           ...
137             Vietnam  85262356.0      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332.0      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743.0      Asia   62.698   2280.769906
140              Zambia  11746035.0    Africa   42.384   1271.211593
141            Zimbabwe  12311143.0    Africa   43.487    469.709298

[142 rows x 5 columns]

In [26]:
filt=df['continent']=='Asia'
df.loc[filt]

                country           pop continent  lifeExp     gdpPercap
0           Afghanistan  3.188992e+07      Asia   43.828    974.580338
7               Bahrain  7.085730e+05      Asia   75.635  29796.048340
8            Bangladesh  1.504483e+08      Asia   64.062   1391.253792
18             Cambodia  1.413186e+07      Asia   59.723   1713.778686
24                China  1.318683e+09      Asia   72.961   4959.114854
55     Hong Kong, China  6.980412e+06      Asia   82.208  39724.978670
58                India  1.110396e+09      Asia   64.698   2452.210407
59            Indonesia  2.235470e+08      Asia   70.650   3540.651564
60                 Iran  6.945357e+07      Asia   70.964  11605.714490
61                 Iraq  2.749964e+07      Asia   59.545   4471.061906
63               Israel  6.426679e+06      Asia   80.745  25523.277100
66                Japan  1.274680e+08      Asia   82.603  31656.068060
67               Jordan  6.053193e+06      Asia   72.535   4519.461171
69     Korea, Dem. Rep.  2.330172e+07      Asia   67.297   1593.065480
70          Korea, Rep.  4.904479e+07      Asia   78.623  23348.139730
71               Kuwait  2.505559e+06      Asia   77.588  47306.989780
72              Lebanon  3.921278e+06      Asia   71.993  10461.058680
78             Malaysia  2.482129e+07      Asia   74.241  12451.655800
83             Mongolia  2.874127e+06      Asia   66.803   3095.772271
87              Myanmar  4.776198e+07      Asia   62.069    944.000000
89                Nepal  2.890179e+07      Asia   63.785   1091.359778
96                 Oman  3.204897e+06      Asia   75.640  22316.192870
97             Pakistan  1.692706e+08      Asia   65.483   2605.947580
101         Philippines  9.107729e+07      Asia   71.688   3190.481016
109        Saudi Arabia  2.760104e+07      Asia   72.777  21654.831940
113           Singapore  4.553009e+06      Asia   79.972  47143.179640
119           Sri Lanka  2.037824e+07      Asia   72.396   3970.095407
124               Syria  1.931475e+07      Asia   74.143   4184.548089
125              Taiwan  2.317429e+07      Asia   78.400  28718.276840
127            Thailand  6.506815e+07      Asia   70.616   7458.396327
137             Vietnam  8.526236e+07      Asia   74.249   2441.576404
138  West Bank and Gaza  4.018332e+06      Asia   73.422   3025.349798
139         Yemen, Rep.  2.221174e+07      Asia   62.698   2280.769906

In [27]:
#b.	Display top and bottom 15 rows
df.head(15)

                   country          pop continent  lifeExp     gdpPercap
0              Afghanistan   31889923.0      Asia   43.828    974.580338
1                  Albania    3600523.0    Europe   76.423   5937.029526
2                  Algeria   33333216.0    Africa   72.301   6223.367465
3                   Angola   12420476.0    Africa   42.731   4797.231267
4                Argentina   40301927.0  Americas   75.320  12779.379640
5                Australia   20434176.0   Oceania   81.235  34435.367440
6                  Austria    8199783.0    Europe   79.829  36126.492700
7                  Bahrain     708573.0      Asia   75.635  29796.048340
8               Bangladesh  150448339.0      Asia   64.062   1391.253792
9                  Belgium   10392226.0    Europe   79.441  33692.605080
10                   Benin    8078314.0    Africa   56.728   1441.284873
11                 Bolivia    9119152.0  Americas   65.554   3822.137084
12  Bosnia and Herzegovina    4552198.0    Europe   74.852   7446.298803
13                Botswana    1639131.0    Africa   50.728  12569.851770
14                  Brazil  190010647.0  Americas   72.390   9065.800825

In [28]:
df.tail(15)

                 country          pop continent  lifeExp     gdpPercap
127             Thailand   65068149.0      Asia   70.616   7458.396327
128                 Togo    5701579.0    Africa   58.420    882.969944
129  Trinidad and Tobago    1056608.0  Americas   69.819  18008.509240
130              Tunisia   10276158.0    Africa   73.923   7092.923025
131               Turkey   71158647.0    Europe   71.777   8458.276384
132               Uganda   29170398.0    Africa   51.542   1056.380121
133       United Kingdom   60776238.0    Europe   79.425  33203.261280
134        United States  301139947.0  Americas   78.242  42951.653090
135              Uruguay    3447496.0  Americas   76.384  10611.462990
136            Venezuela   26084662.0  Americas   73.747  11415.805690
137              Vietnam   85262356.0      Asia   74.249   2441.576404
138   West Bank and Gaza    4018332.0      Asia   73.422   3025.349798
139          Yemen, Rep.   22211743.0      Asia   62.698   2280.769906
140               Zambia   11746035.0    Africa   42.384   1271.211593
141             Zimbabwe   12311143.0    Africa   43.487    469.709298

In [31]:
#c.	Show all the rows where life expectancy is more than 50 years and less than 80 years
filt=((df['lifeExp']>50) & (df['lifeExp']<80))
df.loc[filt]

                country         pop continent  lifeExp     gdpPercap
1               Albania   3600523.0    Europe   76.423   5937.029526
2               Algeria  33333216.0    Africa   72.301   6223.367465
4             Argentina  40301927.0  Americas   75.320  12779.379640
6               Austria   8199783.0    Europe   79.829  36126.492700
7               Bahrain    708573.0      Asia   75.635  29796.048340
..                  ...         ...       ...      ...           ...
135             Uruguay   3447496.0  Americas   76.384  10611.462990
136           Venezuela  26084662.0  Americas   73.747  11415.805690
137             Vietnam  85262356.0      Asia   74.249   2441.576404
138  West Bank and Gaza   4018332.0      Asia   73.422   3025.349798
139         Yemen, Rep.  22211743.0      Asia   62.698   2280.769906

[110 rows x 5 columns]

In [38]:
#d.	Show data for India, America and France
filt=df['country'].isin(['India','America','France'])
df.loc[filt]

   country           pop continent  lifeExp     gdpPercap
44  France  6.108392e+07    Europe   80.657  30470.016700
58   India  1.110396e+09      Asia   64.698   2452.210407

In [51]:
#e.	Show data for all countries where name starts with ‘A’
data=df[df['country'].str.startswith('A')]
data

       country         pop continent  lifeExp     gdpPercap
0  Afghanistan  31889923.0      Asia   43.828    974.580338
1      Albania   3600523.0    Europe   76.423   5937.029526
2      Algeria  33333216.0    Africa   72.301   6223.367465
3       Angola  12420476.0    Africa   42.731   4797.231267
4    Argentina  40301927.0  Americas   75.320  12779.379640
5    Australia  20434176.0   Oceania   81.235  34435.367440
6      Austria   8199783.0    Europe   79.829  36126.492700

In [56]:
#f.	Show min/max and mean GDP and Population for each continent
group=df.groupby('continent').agg({
    'gdpPercap': ['min', 'max', 'mean'],
    'pop': ['min', 'max', 'mean']})
group

              gdpPercap                                   pop                \
                    min          max          mean        min           max
continent
Africa       277.551859  13206.48452   3089.032605   199579.0  1.350312e+08
Americas    1201.637154  42951.65309  11003.031625  1056608.0  3.011399e+08
Asia         944.000000  47306.98978  12473.026870   708573.0  1.318683e+09
Europe      5937.029526  49357.19017  25054.481636   301931.0  8.240100e+07
Oceania    25185.009110  34435.36744  29810.188275  4115771.0  2.043418e+07


                   mean
continent
Africa     1.787576e+07
Americas   3.595485e+07
Asia       1.155138e+08
Europe     1.953662e+07
Oceania    1.227497e+07

In [ ]:


i.	Find top 20 most populous countries
j.	Delete all rows for a specific country
k.	Change all column names to title case
l.	Change column names: pop to Population, gdpPercap to GDP_Percap
m.	Increase Life Expectancy by 2 years for all African countries
n.	Find all the rows that contain NA values
o.	Fill NA values with 0 for numeric columns'''

In [57]:
#g.	Show population and life expectancy for all countries 
df.filter(items=['pop', 'lifeExp'])

            pop  lifeExp
0    31889923.0   43.828
1     3600523.0   76.423
2    33333216.0   72.301
3    12420476.0   42.731
4    40301927.0   75.320
..          ...      ...
137  85262356.0   74.249
138   4018332.0   73.422
139  22211743.0   62.698
140  11746035.0   42.384
141  12311143.0   43.487

[142 rows x 2 columns]

In [ ]:
#h.	Sort the data by country names (ascending) and GDP (descending)