In [31]:
import pandas as pd

In [32]:
data = {'FullName' :['Rucha N','Rohit K', 'Kedar P', 'Ankita G'],
       'Email' : ['Rucha07@gmail.com', 'Rohit.10@gmail.com', 'KedarTennis@gmail.com','Ankita21@gmail.com'],
        'Salary':[100000, 120000,90000,75000]
       }
df = pd.DataFrame(data)
df

   FullName                  Email  Salary
0   Rucha N      Rucha07@gmail.com  100000
1   Rohit K     Rohit.10@gmail.com  120000
2   Kedar P  KedarTennis@gmail.com   90000
3  Ankita G     Ankita21@gmail.com   75000

In [33]:
df.columns = ['Full Name', 'Email', 'Salary']
df

  Full Name                  Email  Salary
0   Rucha N      Rucha07@gmail.com  100000
1   Rohit K     Rohit.10@gmail.com  120000
2   Kedar P  KedarTennis@gmail.com   90000
3  Ankita G     Ankita21@gmail.com   75000

In [34]:
df.columns = [c.lower() for c in df.columns]
df

  full name                  email  salary
0   Rucha N      Rucha07@gmail.com  100000
1   Rohit K     Rohit.10@gmail.com  120000
2   Kedar P  KedarTennis@gmail.com   90000
3  Ankita G     Ankita21@gmail.com   75000

In [35]:
df.columns = list(map(lambda c : c.upper(), df.columns))
df

  FULL NAME                  EMAIL  SALARY
0   Rucha N      Rucha07@gmail.com  100000
1   Rohit K     Rohit.10@gmail.com  120000
2   Kedar P  KedarTennis@gmail.com   90000
3  Ankita G     Ankita21@gmail.com   75000

In [36]:
df.rename(columns = {'FULL NAME': 'FULL_NAME'}, inplace=True)
df

  FULL_NAME                  EMAIL  SALARY
0   Rucha N      Rucha07@gmail.com  100000
1   Rohit K     Rohit.10@gmail.com  120000
2   Kedar P  KedarTennis@gmail.com   90000
3  Ankita G     Ankita21@gmail.com   75000

In [37]:
df.loc[2, 'EMAIL']= 'Kedar11@gmail.com'
df

  FULL_NAME               EMAIL  SALARY
0   Rucha N   Rucha07@gmail.com  100000
1   Rohit K  Rohit.10@gmail.com  120000
2   Kedar P   Kedar11@gmail.com   90000
3  Ankita G  Ankita21@gmail.com   75000

In [38]:
filt = df['SALARY']> 9000
df.loc[filt, 'SALARY'] = df['SALARY'] +2000
df

  FULL_NAME               EMAIL  SALARY
0   Rucha N   Rucha07@gmail.com  102000
1   Rohit K  Rohit.10@gmail.com  122000
2   Kedar P   Kedar11@gmail.com   92000
3  Ankita G  Ankita21@gmail.com   77000

In [39]:
df['SALARY']=df['SALARY'].apply(lambda x : x +1000)
df

  FULL_NAME               EMAIL  SALARY
0   Rucha N   Rucha07@gmail.com  103000
1   Rohit K  Rohit.10@gmail.com  123000
2   Kedar P   Kedar11@gmail.com   93000
3  Ankita G  Ankita21@gmail.com   78000

In [40]:
# df['EMAIL'] = df['EMAIL'].map({'Ankita21@gmail.com':'Ankita_21@gmail.com'})
# df

In [41]:
df['EMAIL'] = df['EMAIL'].replace({'Ankita21@gmail.com':'Ankita_21@gmail.com'})
df

  FULL_NAME                EMAIL  SALARY
0   Rucha N    Rucha07@gmail.com  103000
1   Rohit K   Rohit.10@gmail.com  123000
2   Kedar P    Kedar11@gmail.com   93000
3  Ankita G  Ankita_21@gmail.com   78000